name: blogroll

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          path: rss-combine

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-        

    - name: Build
      working-directory: rss-combine
      run: go build -v ./...

    - uses: actions/checkout@v4
      with:
        repository: uoftwebloggingclub/uoftwebloggingclub.neocities.org
        token: ${{ secrets.GIT_PAT }}
        ref: 'rss'
        path: site

    - name: Run
      working-directory: rss-combine
      run: |
        go run rsscombine.go > /tmp/feed.xml
    
    - name: Copy over publish script tmp
      working-directory: rss-combine
      run: cp ./runner/publish.sh /tmp

    - name: Copy over publish script site
      working-directory: site
      run: cp /tmp/publish.sh ./
    
    - name: Publish to git
      working-directory: site
      run: ./publish.sh
