name: blogroll

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 */2 * * *' # Every 2 hours

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          path: rss-combine
          ref: 'master'

    - uses: actions/checkout@v4
      with:
        repository: uoftwebloggingclub/uoftwebloggingclub.neocities.org
        token: ${{ secrets.GIT_PAT }}
        ref: 'rss-update'
        path: site

    - uses: actions/checkout@v4
      with:
          path: feed
          ref: 'feed'


    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-        

    - name: Build
      working-directory: rss-combine
      run: go build -v ./...

    - name: Run
      working-directory: rss-combine
      run: |
        go run rsscombine.go > /tmp/feed.xml

    - name: Publish to git
      working-directory: feed
      run: bash publish.sh > /tmp/publish.log

    - name: Move trigger_rebuild A
      working-directory: rss-combine
      run: cp ./runner/trigger_rebuild.sh /tmp

    - name: Move trigger_rebuild B
      working-directory: site
      run: cp /tmp/trigger_rebuild.sh ./

    - name: Trigger site rebuild
      working-directory: site
      run: bash  trigger_rebuild.sh
