name: blogroll

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 * * * *' # Every hour

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-        

    - name: Build
      run: go build -v ./...

    - name: Run
      env:
        RSSCOMBINE_TITLE: "UofT Weblogging Club RSS Feed"        
        RSSCOMBINE_DESCRIPTION: "An RSS aggregation of all feeds for members' websites for the UofT Weblogging club"
        RSSCOMBINE_AUTHOR_EMAIL: "uoftwebloggingclub@tutamail.com"        
        RSSCOMBINE_AUTHOR_NAME: "UofT Weblogging Club"
        RSSCOMBINE_FEED_LIMIT_PER_FEED: 10
        RSSCOMBINE_FEED_URLS: "https://raw.githubusercontent.com/uoftwebloggingclub/rsscombine/refs/heads/master/LINKS.md"
        RSSCOMBINE_LINK: "https://uoftwebloggingclub.neocities.org/"

      run: go run rsscombine.go > feed.xml
    
    - name: Publish to neocities
      run: curl -F "feed.xml=@feed.xml" "https://${{  secrets.NEOCITIES_USERNAME  }}:${{  secrets.NEOCITIES_PASSWORD  }}@neocities.org/api/upload"
      
    - uses: gautamkrishnar/keepalive-workflow@v1      
