name: blogroll

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 * * * *' # Every hour

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
          path: rss-combine

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-        

    - name: Build
      working-directory: rss-combine
      run: go build -v ./...

    - uses: actions/checkout@v4
      with:
        repository: uoftwebloggingclub/uoftwebloggingclub.neocities.org
        token: ${{ secrets.GIT_PAT }}
        ref: 'main'
        path: site

    - name: Run
      working-directory: rss-combine
      env:
        RSSCOMBINE_TITLE: "UofT Weblogging Club RSS Feed"        
        RSSCOMBINE_DESCRIPTION: "An RSS aggregation of all feeds for members' websites for the UofT Weblogging club"
        RSSCOMBINE_AUTHOR_EMAIL: "uoftwebloggingclub@gmail.com"        
        RSSCOMBINE_AUTHOR_NAME: "UofT Weblogging Club"
        RSSCOMBINE_FEED_LIMIT_PER_FEED: 10
        RSSCOMBINE_FEED_URLS: "https://uoftwebloggingclub.neocities.org/rss"
        RSSCOMBINE_LINK: "https://uoftwebloggingclub.neocities.org/"
      run: |
        go run rsscombine.go > /tmp/feed.xml
    
    - name: Copy over publish script tmp
      working-directory: rss-combine
      run: cp ./runner/publish.sh /tmp

    - name: Copy over publish script site
      working-directory: site
      run: cp /tmp/publish.sh ./
    
    - name: Publish to git
      working-directory: site
      run: ./publish.sh
  
  keepalive:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: gautamkrishnar/keepalive-workflow@v1
